
GET http://localhost:3005/posts

###
POST http://localhost:3005/posts
Content-Type: application/json

{
    "title": "My First Post",
    "content": "My First Post Content"
}

###
GET http://localhost:3005/posts/5d6a39a8c9d2ef34a71b877e

### 
PATCH  http://localhost:3005/posts/5d6a9f80f8b56066030bf298?parent=5d6a9f80f8b56066030bf298
Content-Type: application/json

{
    "comment": {
        "title": "First Comment",
        "content": "First Comment on First Post"
    }
}

###

DELETE http://localhost:3005/posts/5d6a88fc4e7fa95386c6c2ed